[tox]
envlist = py312, lint, typecheck, build-docs
requires =
    tox-uv>=1.35.1 

[testenv]
package = skip
runner = uv-venv-lock-runner

[testenv:py312]
description = Run tests using pytest
dependency_groups = test
commands =
    pytest {posargs}

[testenv:lint]
description = Run linting using ruff
dependency_groups = lint
skip_install = true
commands =
    ruff check --fix .
    ruff format .

[testenv:typecheck]
description = Run static type checking using mypy
dependency_groups = typecheck
skip_install = true
commands = uv run mypy .

[testenv:build-docs]
description = Build docs using zensical
dependency_groups = build-docs
commands = zensical {posargs:build}
