[project]
site_name = "JET EC Assignment Documentation"
site_dir = "docs/site"
docs_dir = "docs/zensical"
use_directory_urls = false

[theme]
variant = "classic"
features = [
    "navigation.tabs",
    "navigation.sections",
    "content.code.copy"
]

[navigation]
"Home" = "index.md"
"Apps/Example App" = "apps/example_app.md"
"Libraries/Jet API" = "libs/jet_api.md"

[markdown.extensions.mkdocstrings]
handlers.python.options = { heading_level = 2, import_symbols = true, show_source = true, show_root_heading = true, members_order = "alphabetical" }
